### PR TITLE
Tweaking logging

### PR DESCRIPTION
**Pull request by farskipper**
Changes
 * use the krl `.encode()` for json serialization (i.e. regex will output "re#...#")
 * prety-printing the log context

Example output:

```
[EPISODE_START] cj3ospydz0003dudxgnhg59ep
[DEBUG] event/cj3ospydv0002dudxxmtaa7mm/19/pico/root_created | event received: pico/root_created
[DEBUG] event/cj3ospydv0002dudxxmtaa7mm/19/pico/root_created | event added to pico queue: cj3ospydu0001dudxq3jnc6pz
[DEBUG] event/cj3ospydv0002dudxxmtaa7mm/19/pico/root_created | event being processed
[DEBUG] event/cj3ospydv0002dudxxmtaa7mm/19/pico/root_created | rule added to schedule: io.picolabs.pico -> pico_root_created
[DEBUG] event/cj3ospydv0002dudxxmtaa7mm/19/pico/root_created | rule selected: io.picolabs.pico -> pico_root_created
[DEBUG] event/cj3ospydv0002dudxxmtaa7mm/19/pico/root_created | fired
[DEBUG] event/cj3ospydv0002dudxxmtaa7mm/19/pico/root_created | event finished processing
[DEBUG] event/cj3ospydv0002dudxxmtaa7mm/19/pico/root_created | {"directives":[]}
[EPISODE_STOP] cj3ospydz0003dudxgnhg59ep
...
...
...
[DEBUG] query/cj3m5tcwl0002r1dxwxr18ci2/io.picolabs.logging/__testing | query received: io.picolabs.logging/__testing
```

### CODE REVIEW

**Comment by b1conrad** [comment]
that's cool that you can use the krl-stdlib from javascript. and seeing pico objects that way is more appropriate

we had a lively discussion about the virtue of one-line entries vs. the fact that it's new and different vs. some things being lost (pico_id and txn_id)

also came up: the fact that entries are interleaved when the engine is humming through multiple pico evaluations at the same time, and that `grep` becomes usable for dealing with that with the one-liner format

perhaps we could add the pico_id and the event/query part of the `shell_log` to the end of the episode_start line so that a `grep` of part of the latter would find everything about the episode (except episode stop)

**Comment by b1conrad** [comment]
experience report: the pico_id appears in message, e.x. "event added to pico queue: cj3d4gsgh0002kgdddxsh1gw2" so it isn't lost

a downstream tool could be added to the output to do other things to it (e.x. https://github.com/kilianc/rtail )

the `shell_log` part is the same length within an episode, but varies across episodes which has both nice and not-so-nice consequences with interleaving

**Comment by b1conrad** [comment]
hm. got a "[JSObject]" for an error report, which used to print as the message of the Error object, but that is tweakable

**Comment by 0joshuaolson1** [comment]
See https://github.com/Picolab/pico-engine/pull/313 instead

**Pull request closed without merging**
